<?php
include("../connect.php");
$TIGERLION = password_hash("TIGERLION", PASSWORD_DEFAULT);
$SWAGSHOW = password_hash("SWAGSHOW", PASSWORD_DEFAULT);
$LAUGHING = password_hash("LAUGHING", PASSWORD_DEFAULT);
$WONDERBALL = password_hash("WONDERBALL", PASSWORD_DEFAULT);
$THUNDERS = password_hash("THUNDERS", PASSWORD_DEFAULT);
$a[0]="INSERT INTO ADMIN VALUES('ADM_ID_01','VAIBHAV','$TIGERLION')";
$a[1]="INSERT INTO ADMIN VALUES('ADM_ID_02','SOURAV','$SWAGSHOW')";
$a[2]="INSERT INTO ADMIN VALUES('ADM_ID_03','ROMA','$LAUGHING')";
$a[3]="INSERT INTO ADMIN VALUES('ADM_ID_04','RAJAN','$WONDERBALL')";
$a[4]="INSERT INTO ADMIN VALUES('ADM_ID_05', 'KIRAN','$THUNDERS')";
for($i=0;$i<5;$i++) {
    if(mysqli_query($link,$a[$i]))
        echo '<script> alert("Yes") </script>';
}

$DISNEYLAND = password_hash("DISNEYLAND", PASSWORD_DEFAULT);
$APPLECAKE = password_hash("APPLECAKE", PASSWORD_DEFAULT);
$TANGOMAN = password_hash("TANGOMAN", PASSWORD_DEFAULT);
$CHARLIE = password_hash("CHARLIE", PASSWORD_DEFAULT);
$REMORAMBO = password_hash("REMORAMBO", PASSWORD_DEFAULT);
$JAMUNGULAB = password_hash("JAMUNGULAB", PASSWORD_DEFAULT);
$ROUNDING = password_hash("ROUNDING", PASSWORD_DEFAULT);
$TRIANGLE = password_hash("TRIANGLE", PASSWORD_DEFAULT);
$RECTANGLE = password_hash("RECTANGLE", PASSWORD_DEFAULT);
$FORMULA = password_hash("FORMULA", PASSWORD_DEFAULT);
$a[0]="INSERT INTO STUDENT VALUES('AMIT','MISHRA','STU_ID_01','M','CET','$DISNEYLAND','08-04-2020',4789076543,1)";
$a[1]="INSERT INTO STUDENT VALUES('RAJESH','KAPOOR','STU_ID_02','M','JEE','$APPLECAKE','10-04-2020',3867905678,0)";
$a[2]="INSERT INTO STUDENT VALUES('ARJUN','RAO','STU_ID_03','M','CET','$TANGOMAN','12-04-2020',5576894321,1)";
$a[3]="INSERT INTO STUDENT VALUES('ANJALI','MEHTA','STU_ID_04','F','JEE','$CHARLIE','10-04-2020',7896045321,1)";
$a[4]="INSERT INTO STUDENT VALUES('SURESH','RAINA','STU_ID_05','M','CET','$REMORAMBO','08-04-2020',9987687698,0)";
$a[5]="INSERT INTO STUDENT VALUES('MONA','SHA','STU_ID_06','F','CET','$JAMUNGULAB','10-04-2020',9090989765,1)";
$a[6]="INSERT INTO STUDENT VALUES('AISHA','KHAN','STU_ID_07','F','JEE','$ROUNDING','10-042020',8889087867,0)";
$a[7]="INSERT INTO STUDENT VALUES('RAM','PRASAD','STU_ID_08','M','CET','$TRIANGLE','12-04-2020',6758904321,0)";
$a[8]="INSERT INTO STUDENT VALUES('LAL','CHARAN','STU_ID_09','M','CET','$RECTANGLE','08-04-2020',7896543456,1)";
$a[9]="INSERT INTO STUDENT VALUES('ROHAN','MENON','STU_ID_10','M','JEE','$FORMULA','11-04-2020',8909786789,0)";
for($i=0;$i<10;$i++) {
    if(mysqli_query($link,$a[$i]))
        echo '<script> alert("Yes") </script>';
}

$ROSEWATER = password_hash("ROSEWATER", PASSWORD_DEFAULT);
$FLOWER = password_hash("FLOWER", PASSWORD_DEFAULT);
$JUICE = password_hash("JUICE", PASSWORD_DEFAULT);
$ORANGE = password_hash("ORANGE", PASSWORD_DEFAULT);
$ICECAKE = password_hash("ICECAKE", PASSWORD_DEFAULT);
$CRICKET = password_hash("CRICKET", PASSWORD_DEFAULT);
$a[0]="INSERT INTO TEACHER VALUES('RAJ','GOPAL','TEA_PHY_01','$ROSEWATER','PHY','CET',1232314560,'RAJ@GMAIL.COM')";
$a[1]="INSERT INTO TEACHER VALUES('SUHAS','DAS','TEA_MAT_02','$FLOWER','MAT','JEE',4566547894,'SUHAS@GMAIL.COM')";
$a[2]="INSERT INTO TEACHER VALUES('GURU','PRASAD','TEA_CHE_01','$JUICE','CHE','CET',8976545677,'PRASAD@GMAIL.COM')";
$a[3]="INSERT INTO TEACHER VALUES('RANI','DEVI','TEA_PHY_02','$ORANGE','PHY','JEE',9998762234,'RANIDEVI@GMAIL.COM')";
$a[4]="INSERT INTO TEACHER VALUES('SHANTA','NAYAK','TEA_CHE_02','$ICECAKE','CHE','JEE',7727665553,'SNAYAK@GMAIL.COM')";
$a[5]="INSERT INTO TEACHER VALUES('ROHIT','KHOLI','TEA_MAT_01','$CRICKET','MAT','CET',4358907365,'KHOLI@GMAIL.COM')";
for($i=0;$i<6;$i++) {
    if(mysqli_query($link,$a[$i]))
        echo '<script> alert("Yes") </script>';
}